---
title: "Lab9HPC"
author: "Sylvia Baeyens"
date: "10/29/2021"
output:
  github_document: 
    html_preview: false
  html_document: default
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "http://cran.rstudio.com"))
```

```{r packages, echo= FALSE, include= FALSE}
library(data.table)
library(dplyr)
library(tidyverse)
library(leaflet)
library(R.utils)
library(ggplot2)
library(stringr)
```

## Problem 2

```{r}
# generate a n x k dataset with mean lambda
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  return(x)
}
fun1(5,10)

fun1alt <- function(n = 100, k = 4, lambda = 4) {
  matrix(rpois(n*k, lambda), nrow=n, ncol= k)
}
#install.packages("microbenchmark")
library(microbenchmark)
microbenchmark::microbenchmark(
  fun1(),
  fun1alt(), unit="relative"
)

```

```{r}
#find the column max
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
x <- matrix(rnorm(1e4), nrow=10)

# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
}

fun2alt <- function(x) {
  inc = max.col(t(x))
  x[cbind(inc, 1:ncol(x))]
}

all(fun2(x) == fun2alt((x)))

# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x), unit="relative"
)
```

## Problem 3: Parallelize Everything

```{r}
library(parallel)
my_boot <- function(dat, stat, R, ncpus = 1L) {
  
  # Getting the random indices
  n <- nrow(dat)
  idx <- matrix(sample.int(n, n*R, TRUE), nrow=n, ncol=R)
 
  # Making the cluster using `ncpus`
  # STEP 1: GOES HERE- creating a cluster
  cl <- makePSOCKcluster(ncpus)    
  # STEP 2: GOES HERE- preparing a cluster
  clusterExport(cl, c("stat", "dat", "idx"),envir = environment())
  
    # STEP 3: THIS FUNCTION NEEDS TO BE REPLACES WITH parLapply
  ans <- parLapply(cl=cl, seq_len(R), function(i) {
    stat(dat[idx[,i], , drop=FALSE])
  })

  # Coercing the list into a matrix
  ans <- do.call(rbind, ans)
  
  # STEP 4: GOES HERE
  stopCluster(cl)
  ans
  
}
```

```{r}
# Bootstrap of an OLS
my_stat <- function(d) coef(lm(y ~ x, data=d))

# DATA SIM
set.seed(1)
n <- 500; R <- 1e3

x <- cbind(rnorm(n)); y <- x*5 + rnorm(n)

# Checking if we get something similar as lm
ans0 <- confint(lm(y~x))
ans1 <- my_boot(dat = data.frame(x, y), my_stat, R = R, ncpus = 2L)

# You should get something like this
t(apply(ans1, 2, quantile, c(.025,.975)))
```

Is it faster?
```{r}
system.time(my_boot(dat = data.frame(x, y), my_stat, R = 4000, ncpus = 1L))
system.time(my_boot(dat = data.frame(x, y), my_stat, R = 4000, ncpus = 2L))
```

